import "@/app/globals.css";

import { Poppins } from "next/font/google";

import { Navbar } from "@/components/layout/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/react";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "WriteLix",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  // authModal,
}: {
  children: React.ReactNode;
  // authModal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-poppins`}>
        <Navbar />
        <TRPCReactProvider>
          {/* {authModal} */}
          {children}
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
